version: 2
updates:
  - package-ecosystem: npm
    directory: /
    reviewers:
      - "open-turo/node"
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)
      prefix-development: build(dev-deps)
      include: scope
